import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';

const root = fileURLToPath(new URL('../', import.meta.url));
const output = new URL('../lib/client.js', import.meta.url);
const result = await build({
    absWorkingDir: root,
    entryPoints: ['src/client/index.js'],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2022',
    charset: 'utf8',
    write: false,
    legalComments: 'inline',
    banner: { js: '// Generated by npm run build from src/client/. Do not edit directly.' },
});
const source = await format(result.outputFiles[0].text, {
    ...(await resolveConfig(fileURLToPath(output))),
    parser: 'babel',
});

if (process.argv.includes('--check')) {
    if ((await readFile(output, 'utf8')).replace(/\r\n/g, '\n') !== source) {
        throw new Error('lib/client.js is stale. Run npm run build and commit the generated bundle.');
    }
    console.log('Client bundle matches src/client/.');
} else {
    await writeFile(output, source);
    console.log('Built lib/client.js.');
}
